#pragma once

#include <allegro5/allegro.h>

namespace alcpp
{

class Key
{
public:
    enum
    {
        A = ALLEGRO_KEY_A,
        B = ALLEGRO_KEY_B,
        C = ALLEGRO_KEY_C,
        D = ALLEGRO_KEY_D,
        E = ALLEGRO_KEY_E,
        F = ALLEGRO_KEY_F,
        G = ALLEGRO_KEY_G,
        H = ALLEGRO_KEY_H,
        I = ALLEGRO_KEY_I,
        J = ALLEGRO_KEY_J,
        K = ALLEGRO_KEY_K,
        L = ALLEGRO_KEY_L,
        M = ALLEGRO_KEY_M,
        N = ALLEGRO_KEY_N,
        O = ALLEGRO_KEY_O,
        P = ALLEGRO_KEY_P,
        Q = ALLEGRO_KEY_Q,
        R = ALLEGRO_KEY_R,
        S = ALLEGRO_KEY_S,
        T = ALLEGRO_KEY_T,
        U = ALLEGRO_KEY_U,
        V = ALLEGRO_KEY_V,
        W = ALLEGRO_KEY_W,
        X = ALLEGRO_KEY_X,
        Y = ALLEGRO_KEY_Y,
        Z = ALLEGRO_KEY_Z,
        Num0 = ALLEGRO_KEY_0,
        Num1 = ALLEGRO_KEY_1,
        Num2 = ALLEGRO_KEY_2,
        Num3 = ALLEGRO_KEY_3,
        Num4 = ALLEGRO_KEY_4,
        Num5 = ALLEGRO_KEY_5,
        Num6 = ALLEGRO_KEY_6,
        Num7 = ALLEGRO_KEY_7,
        Num8 = ALLEGRO_KEY_8,
        Num9 = ALLEGRO_KEY_9,
        Numpad0 = ALLEGRO_KEY_PAD_0,
        Numpad1 = ALLEGRO_KEY_PAD_1,
        Numpad2 = ALLEGRO_KEY_PAD_2,
        Numpad3 = ALLEGRO_KEY_PAD_3,
        Numpad4 = ALLEGRO_KEY_PAD_4,
        Numpad5 = ALLEGRO_KEY_PAD_5,
        Numpad6 = ALLEGRO_KEY_PAD_6,
        Numpad7 = ALLEGRO_KEY_PAD_7,
        Numpad8 = ALLEGRO_KEY_PAD_8,
        Numpad9 = ALLEGRO_KEY_PAD_9,
        F1 = ALLEGRO_KEY_F1,
        F2 = ALLEGRO_KEY_F2,
        F3 = ALLEGRO_KEY_F3,
        F4 = ALLEGRO_KEY_F4,
        F5 = ALLEGRO_KEY_F5,
        F6 = ALLEGRO_KEY_F6,
        F7 = ALLEGRO_KEY_F7,
        F8 = ALLEGRO_KEY_F8,
        F9 = ALLEGRO_KEY_F9,
        F10 = ALLEGRO_KEY_F10,
        F11 = ALLEGRO_KEY_F11,
        F12 = ALLEGRO_KEY_F12,
        Escape = ALLEGRO_KEY_ESCAPE,
        Tilde = ALLEGRO_KEY_TILDE,
        Minus = ALLEGRO_KEY_MINUS,
        Equals = ALLEGRO_KEY_EQUALS,
        Backspace = ALLEGRO_KEY_BACKSPACE,
        Tab = ALLEGRO_KEY_TAB,
        OpenBrace = ALLEGRO_KEY_OPENBRACE,
        CloseBrace = ALLEGRO_KEY_CLOSEBRACE,
        Enter = ALLEGRO_KEY_ENTER,
        SemiColon = ALLEGRO_KEY_SEMICOLON,
        Quote = ALLEGRO_KEY_QUOTE,
        Backslash = ALLEGRO_KEY_BACKSLASH,
        Comma = ALLEGRO_KEY_COMMA,
        FullStop = ALLEGRO_KEY_FULLSTOP,
        Slash = ALLEGRO_KEY_SLASH,
        Space = ALLEGRO_KEY_SPACE,
        Insert = ALLEGRO_KEY_INSERT,
        Delete = ALLEGRO_KEY_DELETE,
        Home = ALLEGRO_KEY_HOME,
        End = ALLEGRO_KEY_END,
        PageUp = ALLEGRO_KEY_PGUP,
        PageDown = ALLEGRO_KEY_PGDN,
        Left = ALLEGRO_KEY_LEFT,
        Right = ALLEGRO_KEY_RIGHT,
        Up = ALLEGRO_KEY_UP,
        Down = ALLEGRO_KEY_DOWN,
        NumpadSlash = ALLEGRO_KEY_PAD_SLASH,
        NumpadAsterisk = ALLEGRO_KEY_PAD_ASTERISK,
        NumpadMinus = ALLEGRO_KEY_PAD_MINUS,
        NumpadPlus = ALLEGRO_KEY_PAD_PLUS,
        NumpadDelete = ALLEGRO_KEY_PAD_DELETE,
        NumpadEnter = ALLEGRO_KEY_PAD_ENTER,
        PrintScreen = ALLEGRO_KEY_PRINTSCREEN,
        Pause = ALLEGRO_KEY_PAUSE,
        Command = ALLEGRO_KEY_COMMAND,
        LeftShift = ALLEGRO_KEY_LSHIFT,
        RightShift = ALLEGRO_KEY_RSHIFT,
        LeftControl = ALLEGRO_KEY_LCTRL,
        RightControl = ALLEGRO_KEY_RCTRL,
        Alt = ALLEGRO_KEY_ALT,
        AltGr = ALLEGRO_KEY_ALTGR,
        LeftWin = ALLEGRO_KEY_LWIN,
        RightWin = ALLEGRO_KEY_RWIN,
        Menu = ALLEGRO_KEY_MENU,
        ScrollLock = ALLEGRO_KEY_SCROLLLOCK,
        NumLock = ALLEGRO_KEY_NUMLOCK,
        CapsLock = ALLEGRO_KEY_CAPSLOCK,
        Max = ALLEGRO_KEY_MAX
    };
};

class KeyModifiers
{
public:
    enum
    {
        Shift = ALLEGRO_KEYMOD_SHIFT,
        Ctrl = ALLEGRO_KEYMOD_CTRL,
        Alt = ALLEGRO_KEYMOD_ALT,
        LWin = ALLEGRO_KEYMOD_LWIN,
        RWin = ALLEGRO_KEYMOD_RWIN,
        Menu = ALLEGRO_KEYMOD_MENU,
        AltGr = ALLEGRO_KEYMOD_ALTGR,
        Command = ALLEGRO_KEYMOD_COMMAND,
        ScrollLock = ALLEGRO_KEYMOD_SCROLLLOCK,
        NumLock = ALLEGRO_KEYMOD_NUMLOCK,
        CapsLock = ALLEGRO_KEYMOD_CAPSLOCK
    };
};

}